kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeployments
spec:
   replicas: 3
   selector:     
    matchLabels:
     name: deployment
   template:
     metadata:
       name: deploy-pod
       labels:
         name: deployment
     spec:
      containers:
        - name: con1
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo test deploy 2; sleep 5; done"]
